# Pamplona 2020
#  Playbook which starts ASM 
---

- name : "starting {{item}} with srvctl"
  shell: "{{oracle_home}}/bin/srvctl start asm "
  register: command_output
  environment:
      ORACLE_HOME: "{{oracle_home}}"
      ORACLE_SID:  "{{oracle_sid}}"
      PATH: "$PATH:${{oracle_home}}:/bin:/usr/bin:/bin:/usr/local/bin:/sbin"
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:${{oracle_home}}/lib"
  ignore_errors: true 

- name: registering srvctl start   information 
  blockinfile:
      path: "{{logfile}}"
      marker: ""
      insertafter: EOF
      block: |
            # --------------------- stopping {{oracle_sid}}  -----------------------
             {{command_output.stdout}}
             {{command_output.stderr}}
  
- name : checkif asm is UP 
  shell: "ps -ef |grep pmon |grep -v grep |grep -v {{item}}"
  environment: 
    PATH: "$PATH:/bin:/usr/bin:/bin:/usr/local/bin:/sbin"
  ignore_errors: yes   
  register: sid_running

- name: IF ASM is  down  we exit with fail msg
  fail: 
     msg: "ERROR: ASm did not startup "
  when: "{{ sid_running.stdout_lines|length }} == 0"
  
  
