# Pamplona 2020
#  Playbook which check if oracle is active
---
- name : check if {{oracle_sid}} is running
  shell: "ps -ef |grep ora_pmon |grep -v grep |grep {{item}} "
  environment:
     PATH: "$PATH:/bin:/usr/bin:/bin:/usr/local/bin:/sbin"
  ignore_errors: yes   
  register: sid_running

- name: registering db_status
  set_fact:
    shutted_down: true
  when: "{{ sid_running.stdout_lines|length }} == 0"

- name: registering srvctl stop   information (ok)
  blockinfile:
    path: "{{logfile}}"
    block: "OK: no pmon process runnig for database, the database {{item}} is down "
    marker: ""
    insertafter: EOF
  when: "{{ sid_running.stdout_lines|length }} == 0"

- name: registering srvctl stop   information (error)
  blockinfile:
    path: "{{logfile}}"
    insertafter: EOF
    marker: ""
    block: |
      "WARNING: {{ sid_running.stdout_lines|length }} ora_pmon{{item}} actives, stopping  database by sqlplus"
  when: "{{ sid_running.stdout_lines|length }} > 0"