# Pamplona 2020
#  Playbook which starts databases
---
- name: "starting {{oracle_sid}} database"
  set_fact:
    shutted_down: true
 
- name: "Logging   {{oracle_sid}}"
  blockinfile:
    path: "{{logfile}}"
    marker: ""
    insertafter: EOF
    block: |
        #--------------------- shutting down {{oracle_sid}}  -----------------------
  when: activo|bool

- include: tasks/srvctl_db_start.yml
  when: activo|bool

- include: tasks/check_running_SID.yml
  when: activo|bool

- include: tasks/sqlplus_db_shutdown.yml
  when: activo|bool  and  shutted_down |bool

 
- name : checkif {{item}}}} is UP 
  shell: "ps -ef |grep pmon |grep -v grep |grep -v {{item}}"
  environment: 
    PATH: "$PATH:/bin:/usr/bin:/bin:/usr/local/bin:/sbin"
  ignore_errors: yes   
  register: sid_running

- name: "IF {{itm}}}} is  down  we exit with fail msg"
  fail: 
     msg: "ERROR: {{ITEM}} database  did not startup "
  when: "{{ sid_running.stdout_lines|length }} == 0"