# Pamplona 2019 
#   Playbook wich  stops and starts all the S.O  running resources 
#   It will write a  file with the current setup of the database at HOME/logs/DATE_TIME_SHUTDOWN_ansible_date.log
#  requires
#    req:                              request number in order to create the blockout
#    operation:                          acton [stop|start]
---
- name: gather local facts 
  script: files/create_facts.sh
  when: operation|lower =="stop"

- name: setting LOG variable
  set_fact:
      logfile: "{{oracle_user_home}}/logs/{{ ansible_date_time.date}}:{{ansible_date_time.time}}_{{operation|upper}}_by_ANSIBLE.log"

- name: setting header at logfile  
  blockinfile:  
      path: "{{logfile}}"
      create : yes
      marker: ""  
      insertbefore: BOF
      block: |
             ## current status of server {{env}} at {{ ansible_date_time.date}}:{{ansible_date_time.time}}"        
 
# name: stop
# include: tasks/stop_all.yml 
#  when: operation|lower =="stop"

- name: start 
  include: tasks/start_all.yml
  when: operation|lower =="start"
