# Pamplona 2019 
#   Playbook wich  stops and starts all the S.O  running resources 
#   It will write a  file with the current setup of the database at HOME/logs/DATE_TIME_SHUTDOWN_ansible_date.log
#  
#  
---
- name: gather local facts 
  script: files/create_facts.sh

- name: setting header at logfile  
  blockinfile:  
    path: "{{logfile}}"
    marker: "" 
    insertafter: EOF
    block: |
      \#############################################################
      \#################   Gathering server info  \###################
      \##############################################################
  
- include: tasks/agent.yml
  vars:
    duration: "04:00"
    agent_action: create 

- include: tasks/agent.yml
  vars:
    agent_action: "{{operation}}"

- include: tasks/gather_so.yml 

- include: tasks/gather_ASM.yml
  vars:
    oracle_sid: "{{item}}"
    oracle_home: "{{hostvars['alone.pamplona.name']['ansible_facts']['ansible_local']['asm'][item]['oracle_home']}}"
  with_items: "{{ansible_facts.ansible_local.asm}}"

- include: tasks/gather_SID.yml
  vars:
    oracle_sid: "{{item}}"
    oracle_home: "{{hostvars['alone.pamplona.name']['ansible_facts']['ansible_local']['databases'][item]['oracle_home']}}"
  with_items: "{{ansible_facts.ansible_local.databases}}"

- name: Logging  Stop actions 
  blockinfile:  
    path: "{{logfile}}"
    marker: ""  
    insertafter: EOF
    block: |
      #############################################################
      #################   Starting stop actions ###################
      ############################################################
   
- include: tasks/listener_shutdown.yml
  vars:
    listener_name: "{{item}}"
    oracle_home: "{{hostvars['alone.pamplona.name']['ansible_facts']['ansible_local']['listeners'][item]['oracle_home']}}"
  with_items: "{{ansible_facts.ansible_local.listeners}}"
   
- include: tasks/databases_shutdown.yml
  vars:
    oracle_sid: "{{item}}"
    oracle_home: "{{hostvars['alone.pamplona.name']['ansible_facts']['ansible_local']['databases'][item]['oracle_home']}}"
    activo:  "{{hostvars['alone.pamplona.name']['ansible_facts']['ansible_local']['databases'][item]['activo']}}"
  with_items: "{{ansible_facts.ansible_local.databases}}"

- include: tasks/asm_shutdown.yml
  vars:
    oracle_sid: "{{item}}"
    oracle_home: "{{hostvars['alone.pamplona.name']['ansible_facts']['ansible_local']['asm'][item]['oracle_home']}}"
  with_items: "{{ansible_facts.ansible_local.asm}}"
  
- name : Checking again if evrything is stopped 
  shell: "ps -axf|grep -v grep |grep smon "
  environment: 
     PATH: "$PATH:/bin:/usr/bin:/bin:/usr/local/bin:/sbin"
  ignore_errors: yes   
  register: sid_running
  
- name: "Logging if  we havent stopped all the databases  "
  blockinfile:
    path: "{{logfile}}"
    marker: ""
    insertafter: EOF
    block: |
      ERROR: some database is running.
      Shutdown process has failed.
      Please contact with oracle dba team
      -- result output ----
      {{sid_running.stdout}}
      -- result output ----
  when: "{{ sid_running.stdout_lines|length }} > 0"

- name: IF any smon is running we exit with fail msg
  fail: 
     msg: "ERROR: some database is running, please contact with oracle dba team"
  when: "{{ sid_running.stdout_lines|length }} > 0"


- name : registering at log the remaining running processes  
  shell: "ps -axf "
  environment: 
     PATH: "$PATH:/bin:/usr/bin:/bin:/usr/local/bin:/sbin"
  ignore_errors: yes   
  register: sid_running

- name: setting header  
  blockinfile:  
    path: "{{logfile}}"
    marker: "--#################   All database processes stpped   ###################"  
    insertafter: EOF
    block: |
      {{sid_running.stdout}}
      ########################################################################
       End of process at  "{{ ansible_date_time.date}}:{{ansible_date_time.time}}"